name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build API image
        run: docker build -t portfolio_api:latest -f apps/api/Dockerfile .

      - name: Build Web image
        run: docker build -t portfolio_web:latest -f apps/web/Dockerfile --build-arg NEXT_PUBLIC_API_URL=https://akkila.dev/v1 --build-arg NEXT_PUBLIC_API_URL_ORIGIN=https://akkila.dev .

      - name: Deploy
        run: docker compose -f /apps/portfolio/compose.yml up -d --no-build
